# Generated by Django 3.2.25 on 2024-05-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
